### PR TITLE
add languages

### PR DESCRIPTION
**Pull request by hennychen**
add chinese language

### CODE REVIEW

**Comment by rodica-andronache** [comment]
Hello @hennychen ,

Thank you so much for your contribution, we really appreciate it. Could you please make a fork from our development brach , make you changes and than make the pull request to development?
This way we can test all the commits before releasing an update on production.

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi @hennychen,

If you want I can move the changes to development. Just let me know.

Regards,
Rodica

**Comment by hennychen** [comment]
ok

**Comment by rodica-andronache** [comment]
Hi @hennychen,

I moved your changes to the development branch, and it will be available in the next update.
Thank you again for your contribution.

Best regards,
Rodica

**Pull request closed without merging**
